apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: calico-default-deny
spec:
  order: 2000
  selector: "projectcalico.org/namespace == 'demo'"
  types:
  - Ingress
  - Egress
