---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx
  namespace: demo
spec:
  selector:
    matchLabels:
      app: open-nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: open-nginx
    spec:
      containers:
      - name: open-nginx
        image: nginx
        ports:
        - containerPort: 80
        resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: open-nginx
  namespace: demo
  labels:
    run: open-nginx-svc
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: open-nginx
